### ISSUE TITLE
rune color, cataclysm classic

### ISSUE THREAD

**Issue by Megumin230** [AggroBird/umberrunes#2]
All the runes are the same color, in cataclysm dks still use all 3 different runes and death runes
and with sorting runes option, I have no idea which rune is in cooldown 
![image](https://github.com/AggroBird/umberrunes/assets/70694639/d488d6e1-7f76-461f-bd18-107c4df6afae)

**Comment by AggroBird** [comment]
Fixed in version 1.12.1
